### ISSUE TITLE
5 test failures in Xcd when using Eigen 3.3

### ISSUE THREAD

**Issue by iamthad** [marcel-goldschen-ohm/EigenLab#8]
The following test results occur using Eigen 3.3~beta1-2 on Ubuntu 16.04

    ...
    Test coefficient-wise abs(a): FAIL
    Test coefficient-wise sqrt(a): FAIL
    Test coefficient-wise exp(a): FAIL
    Test coefficient-wise log(a): FAIL
    Test coefficient-wise log10(a): FAIL
    ...
    Test summary, number of failures: Xd=0 Xf=0 Xi=0 Xcd=5

**Comment by marcel-goldschen-ohm** [comment]
Hmm, I don't get this error on MacOSX. The failed tests are for complex double types. Perhaps I need some casts to real values for those ops. I'll look into it. However, if you don't need complex matrices, it's not an issue.

**Comment by marcel-goldschen-ohm** [comment]
I can't reproduce this. If you still get this error for the most up to date version, please let me know/reopen as an issue.

**Comment by iamthad** [comment]
I just ran a bisect and it appears commit ee6e82c fixed this issue. Thanks for looking into it!

**Comment by marcel-goldschen-ohm** [comment]
Great!
