### ISSUE TITLE
Template substitution errors

### ISSUE THREAD

**Issue by CsatiZoltan** [marcel-goldschen-ohm/EigenLab#9]
I installed Eigen 3.3.1 and when I wanted to try out the code in [this section](https://github.com/marcel-goldschen-ohm/EigenLab#example-eigenlab-command-shell-similar-to-matlab), it threw the errors attached. I used `g++ -std=c++11 code.cpp`, where `code.cpp` is the code from the cited section and the Eigen folder is placed in the main directory.

[errorMessage.txt](https://github.com/marcel-goldschen-ohm/EigenLab/files/649573/errorMessage.txt)

**Comment by marcel-goldschen-ohm** [comment]
Looks like something to do with complex values, a capability that was added after I wrote that example code. I'll look into it.

**Comment by marcel-goldschen-ohm** [comment]
I had no errors with this code using Eigen 3.2.9, but after updating to Eigen 3.3.3 I got an error based on the return type of log(), which is different than the errors you mention (maybe specific to version 3.3.1?). I updated EigenLab.h to handle this, so now the command line program as in the README (I also added a CmdLine.cpp file to tests/) works for me with Eigen 3.3.3.
